export default[
    {
        id: 1,
        img: "./images/japan.jpg",
        country: "J A P A N",
        location_link: "www.google.com",
        place: "Mount Fuji",
        date:"12 Jan 2021-24 Jan 2021",
        description:"Mount Fuji is the tallest mountain in Japan, standing at 3,776 meters (12,380 feet). Mount Fuji is the single most popular tourist site in Japan, for both Japanese and foreign tourists",
    },
    {
        id: 2,
        img: "./images/australia.jpg",
        country:"AUSTRALIA",
        location_link:"www.google.com",
        place:"Austri Dam",
        date:"12 Feb 2021-24 April 2021",
        description:"Mount Fuji is the tallest mountain in Japan, standing at 3,776 meters (12,380 feet). Mount Fuji is the single most popular tourist site in Japan, for both Japanese and foreign tourists",
    },
    {
        id: 3,
        img: "./images/egypt.jpg",
        country:"E G Y P T",
        location_link:"www.google.com",
        place:"Sahara",
        date:"12 May 2021-24 June 2021",
        description:"Mount Fuji is the tallest mountain in Japan, standing at 3,776 meters (12,380 feet). Mount Fuji is the single most popular tourist site in Japan, for both Japanese and foreign tourists",
    },
    {
        id: 4,
        img: "./images/italy.jpg",
        country:"I T A L Y",
        location_link:"www.google.com",
        place:"St. Venice",
        date:"12 July 2021-24 Aug 2021",
        description:"Mount Fuji is the tallest mountain in Japan, standing at 3,776 meters (12,380 feet). Mount Fuji is the single most popular tourist site in Japan, for both Japanese and foreign tourists",
    },
    {
        id: 5,
        img: "./images/jaipur.jpg",
        country:"J A I P U R",
        location_link:"www.google.com",
        place:"Amrush Temple",
        date:"12 Aug 2021-24 Sep 2021",
        description:"Mount Fuji is the tallest mountain in Japan, standing at 3,776 meters (12,380 feet). Mount Fuji is the single most popular tourist site in Japan, for both Japanese and foreign tourists",
    },
    {
        id: 6,
        img:"./images/norway.jpg",
        country:"N O R W A Y",
        location_link:"www.google.com",
        place:"Costa Roca",
        date:"12 Oct 2021-24 Dec{} 2021",
        description:"Mount Fuji is the tallest mountain in Japan, standing at 3,776 meters (12,380 feet). Mount Fuji is the single most popular tourist site in Japan, for both Japanese and foreign tourists",
    },

]